### ISSUE TITLE
A minor displacement of circle while in horizontal orientation mode

### ISSUE THREAD

**Issue by pchettiy** [k0shk0sh/FastAccess#7] opened 2016-11-06 04:36 UTC
As you can see [here](http://i.imgur.com/UERX2hn.gif) there seems to be this minor movement.

**Comment by pchettiy** [comment] 2016-11-06 04:43
It may be a device related issue, the displacement occurs often but not all the time.

**Comment by k0shk0sh** [comment] 2016-11-06 04:50
Thank you very much for your continues help & feedback, i really appreciate your effort. 
To comment on the picture you sent, it seems to be working as intended as basically this is how the animate works, when you open the apps, basically the position changes with an animation, it might doesn't look that pretty but its an animation :p, i'll try and improve it in the next release. perhaps later today as I'm creating an intro screen to describe how stuff works in FA. Thank you very much man.

**Comment by k0shk0sh** [comment] 2016-11-06 04:58
in a second thought, its a device related issue, as does flicker does not work in my HTC M8. will try and figure out what is going on.

**Comment by k0shk0sh** [comment] 2016-11-06 07:25
This issue has been fixed and im uploading new update right away to the play store. i'll close it for the meantime, after you get the update and if you still get that issue (which i doubt it) please re-open it. thank you very much for your help.

**Closed as completed by k0shk0sh** 2016-11-06 07:25 UTC
Labels: bug

**Comment by k0shk0sh** [comment] 2016-11-06 15:11
Hello there, could you please verify the issue is resolved. Thanks

**Comment by pchettiy** [comment] 2016-11-06 16:03
Yep, resolved. Great job!
